### ISSUE TITLE
Toolkit somethimes breaks while running and can't be restarted anymore

### ISSUE THREAD

**Issue by Endebert** [reTHINK-project/dev-hyperty-toolkit#11]
Sometimes the toolkit stops working after a while. When it breaks, it can't be restarted anymore, unless I revert the folder to its initial state.

Output when the error occurs:
```
...
[BS] Browser Connected: Chromium, version: 50.0.2661.102
[BS] Browser Connected: Chromium, version: 50.0.2661.102
[BS] Browser Connected: Chromium, version: 50.0.2661.102
src/room-ui /home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/src/room-ui false
[15:32:57] Copy changes from RoomUIReporter.hy.js to /home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/src/room-ui
src/room-ui /home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/src/room-ui false
[15:32:57] Copy changes from RoomUIObserver.hy.js to /home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/src/room-ui
[15:32:57] -----------------------------------------------------------
[15:32:57] Converting RoomUIObserver.hy.js from ES6 to ES5
[15:32:57] -----------------------------------------------------------
[15:32:57] Converting RoomUIObserver.hy.js from ES6 to ES5
[15:32:58] Resource:  /home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/resources/RoomUIObserver.hy.js
[15:32:58] Encoding:  resources/ RoomUIObserver.hy {"configuration":{},"isDefault":false,"descriptor":"Hyperties"}
[15:32:58] Resource:  /home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/resources/RoomUIObserver.hy.js
[15:32:58] Encoding:  resources/ RoomUIObserver.hy {"configuration":{},"isDefault":false,"descriptor":"Hyperties"}
[15:32:58] Encode:  /home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/resources/RoomUIObserver.hy.js
[15:32:58] setting configuration:  {}
[15:32:58] Encode:  /home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/resources/RoomUIObserver.hy.js
undefined:1



SyntaxError: Unexpected end of input
    at Object.parse (native)
    at DestroyableTransform._transform (/home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/Gulpfile.js:544:21)
    at DestroyableTransform.Transform._read (/home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at write (/home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)

npm ERR! Linux 3.13.0-88-generic
npm ERR! argv "/home/ren-local/.nvm/versions/node/v5.4.0/bin/node" "/home/ren-local/.nvm/versions/node/v5.4.0/bin/npm" "run" "start:dev"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! dev-hyperty-toolkit@0.2.1 start:dev: `gulp serve --dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dev-hyperty-toolkit@0.2.1 start:dev script 'gulp serve --dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dev-hyperty-toolkit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve --dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls dev-hyperty-toolkit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/npm-debug.log
```

Output when trying to restart the toolkit:
```
% npm run start:dev                                                                                       ~/IdeaProjects/rethink/dev-hyperty-toolkit
Now using node v5.4.0 (npm v3.3.12)

> dev-hyperty-toolkit@0.2.1 start:dev /home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit
> gulp serve --dev

[15:37:08] Using gulpfile ~/IdeaProjects/rethink/dev-hyperty-toolkit/Gulpfile.js
[15:37:08] Starting 'serve'...
[15:37:08] Starting 'environment'...
[15:37:08] To use the environment variables you need use
export DEVELOPMENT=true|false
export DOMAIN=<your domain>
export RUNTIME_URL=<runtime location> (optional)
[15:37:08] For default the settings applied are in the system.config.json file
[15:37:08] You are in the develop mode
[15:37:08] Your configuration 
 {
  "development": true,
  "runtimeURL": "hyperty-catalogue://hybroker.rethink.ptinovacao.pt/.well-known/runtime/Runtime",
  "domain": "hybroker.rethink.ptinovacao.pt"
}
[15:37:08] Finished 'environment' after 28 ms
[15:37:08] Starting 'clean'...
[15:37:08] Finished 'clean' after 41 ms
[15:37:08] Starting 'src-hyperties'...
[?] Where is dev-hyperty? dev-hyperty
[15:37:14] Starting 'copy-src'...
[15:37:14] Finished 'copy-src' after 104 ms
[15:37:14] Starting 'copy-examples'...
[15:37:14] Finished 'copy-examples' after 54 ms
[15:37:14] Finished 'src-hyperties' after 6.33 s
[15:37:14] Starting 'schemas'...
[15:37:14] Resource:  /home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/src/hello-world/HelloWorldDataSchema.ds.json
[15:37:14] Encoding:  resources/ HelloWorldDataSchema.ds {"configuration":{},"isDefault":false,"descriptor":"DataSchemas"}
[15:37:14] -----------------------------------------------------------
[15:37:14] Encoding HelloWorldDataSchema.ds.json to base64
[15:37:14] Encode:  /home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/src/hello-world/HelloWorldDataSchema.ds.json
[15:37:14] setting configuration:  {}
[15:37:14] DataSchema HelloWorldDataSchema.ds  was encoded
[15:37:14] -----------------------------------------------------------
...
[15:37:14] Resource:  /home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/resources/schemas/SyncDataObject.ds.json
[15:37:14] Encoding:  resources/ SyncDataObject.ds {"configuration":{},"isDefault":false,"descriptor":"DataSchemas"}
[15:37:14] -----------------------------------------------------------
[15:37:14] Encoding SyncDataObject.ds.json to base64
[15:37:14] Encode:  /home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/resources/schemas/SyncDataObject.ds.json
[15:37:14] setting configuration:  {}
[15:37:14] DataSchema SyncDataObject.ds  was encoded
[15:37:14] -----------------------------------------------------------
[15:37:14] Finished 'schemas' after 95 ms
[15:37:14] Starting 'js'...
[15:37:14] -----------------------------------------------------------
[15:37:14] Converting main.js from ES6 to ES5
[15:37:16] The main file was created like a distribution file on /dist
[15:37:16] -----------------------------------------------------------
[15:37:16] Finished 'js' after 1.28 s
[15:37:16] Starting 'hyperties'...
[15:37:16] -----------------------------------------------------------
[15:37:16] Converting BraceletSensorObserver.hy.js from ES6 to ES5
[15:37:17] Resource:  /home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/resources/BraceletSensorObserver.hy.js
[15:37:17] Encoding:  resources/ BraceletSensorObserver.hy {"configuration":{},"isDefault":false,"descriptor":"Hyperties"}
[15:37:17] Encode:  /home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/resources/BraceletSensorObserver.hy.js
undefined:1



SyntaxError: Unexpected end of input
    at Object.parse (native)
    at DestroyableTransform._transform (/home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/Gulpfile.js:544:21)
    at DestroyableTransform.Transform._read (/home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at write (/home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)

npm ERR! Linux 3.13.0-88-generic
npm ERR! argv "/home/ren-local/.nvm/versions/node/v5.4.0/bin/node" "/home/ren-local/.nvm/versions/node/v5.4.0/bin/npm" "run" "start:dev"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! dev-hyperty-toolkit@0.2.1 start:dev: `gulp serve --dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dev-hyperty-toolkit@0.2.1 start:dev script 'gulp serve --dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dev-hyperty-toolkit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve --dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls dev-hyperty-toolkit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/npm-debug.log
```

**Comment by vitormsilva** [comment]
I don't know when or how this happens.. 

When this happens do `git checkout resources/descriptors/hyperties.json`;

If someone found how to reproduce this error, let me know;

**Comment by Endebert** [comment]
I haven't encountered this error in quite some time now, so I'm going ahead and close this issue.
