### ISSUE TITLE
Add "isobject" to dependencies

### ISSUE THREAD

**Issue by Endebert** [reTHINK-project/dev-hyperty-toolkit#18]
Please add the module "isobject" to the dependencies. Related error (with newly cloned dev-hyperty-toolkit):
```
> dev-hyperty-toolkit@0.3.0 start:dev /home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit
> gulp serve --dev

module.js:328
    throw err;
    ^

Error: Cannot find module 'isobject'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ren-local/IdeaProjects/rethink/dev-hyperty-toolkit/node_modules/fill-range/index.js:10:16)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

```

**Comment by Endebert** [comment]
May have been related to my old node version. Tried reinstalling the toolkit with the current NodeJs version, and this error seems not to occur anymore.
